default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV.fetch("RAILS_DB_HOST") {'db'} %>
  password: <%= ENV.fetch("RAILS_DB_PASSWORD") {'password'} %>
  database: <%= ENV.fetch("RAILS_DB_NAME") {'app_db'} %>
  pool: 5

common:
  <<: *default
  host: <%= ENV["COMMON_DATABASE_HOST"] {'db'}%>
  password: <%= ENV["COMMON_DATABASE_PASSWORD"] {'password'}%>
  database: <%= ENV["COMMON_DATABASE_NAME"] {'app_db'}%>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
